public class throwexception2 {
    public static void main(String[] args) {
        System.out.println(10/0);
        System.out.println("Hello");
    
}
}
     //RE-ArithmeticException







// public class throwexception2 {
//         public static void main(String[] args) {
//             throw new ArithmeticException("/by zero");
//             System.out.println("Hello");
        
//     }
//     }
    //   RE-Unreachable statement
    // if we write something directly after throw statement , we will get compile time error saying unreachable statement.